### PR TITLE
Migrate org.jetbrains.annotations to android.support.annotation

### PR DESCRIPTION
**Pull request by InnoLuke**
This fixes a build error when using R8

### CODE REVIEW

**Comment by InnoLuke** [comment]
Hi mate, cheers for this great library.

Sadly, I can't use it in projects using R8 - builds fail with the message:
`Program type already present: org.intellij.lang.annotations.JdkConstants$ListSelectionMode`

Would appreciate if you could merge this fix so my fellow R8ers can enjoy maskable layouts too :-)

**Comment by christophesmet** [comment]
Thanks a lot for looking into this!
It's hard to find the time to update the library to the latest tools and Kotlin.
I'm gonna make some effort and finish it, thank you for submitting this in the meantime :)

**Comment by InnoLuke** [comment]
No worries mate, I know exactly how you feel. Thanks for the extremely speedy merge

**Comment by InnoLuke** [comment]
Would you mind also making a release for Jitpack?

**Comment by christophesmet** [comment]
Sure, the artifact should be available on jitpack.
Everything working ?

**Comment by InnoLuke** [comment]
Not yet, I'll take another look tomorrow

**Pull request merged**
